spring:
  application:
    name: wxl-proxy
  pid:
    file: proxy.pid

logging:
  level:
    com.wxl.proxy: debug
    root: info
  path: logs/

proxy:
  boss-threads: 0
  work-threads: 0
  tcp:
    server:
      mysql-proxy:
        bind-port: 9999
        remote-host: localhost
        remote-port: 3306
      redis-proxy:
        bind-port: 9998
        remote-host: localhost
        remote-port: 6379
  http:
    bind-port: 8888
    connect-timeout: 5s
    second-proxy:
      host: localhost
      port: 1080
      type: socks5


